fixtures:
  repositories:
    apache: https://github.com/puppetlabs/puppetlabs-apache.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib
  symlinks:
    mod_auth_cas: "#{source_dir}"
